services:
  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init-lite.sh:/docker-entrypoint-initdb.d/mongo-init-lite.shit-lite.sh
      - ../db/opendfoodfact_skrinked.gz:/data/filtered_mongodb_archive.gz
    environment:
      MONGO_INITDB_DATABASE: openfoodfacts
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["mongod", "--bind_ip_all"]

  aletheia-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: aletheia-server
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8080"  # Change the host port to 8081
    environment:
      DATABASE_URL: "mongodb://root:example@mongodb:27017/openfoodfacts?authSource=admin"

volumes:
  mongodb_data: